### ISSUE TITLE
Terminal doesn't scroll to the bottom in hsplit

### ISSUE THREAD

**Issue by anaisbetts** [atom-archive/terminal#10]
Set up a window like this:

![image](https://f.cloud.github.com/assets/1396/1092257/9e85e0dc-1678-11e3-8e16-6db3d68b47c7.png)

Then run some commands - the scroll won't follow the active prompt, so you end up having to scroll all the time

**Comment by lmartins** [comment]
Having the same problem here.

**Comment by ajmath** [comment]
+1

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
