### ISSUE TITLE
Terminal cursor defaults to the begginning of the line

### ISSUE THREAD

**Issue by dsorkin** [atom-archive/terminal#12]
Any time I have the terminal open in Atom, the cursor is positioned at the beginning or in the middle of the text in my terminal prompt. I can type and execute a command, and the output looks fine. I have a weird set up that's created from [a fork of my developer buddy's .files](https://github.com/dsorkin/.files). I'm also running tmux and powerline if that has anything to do with it.

![terminal_-__users_dereksorkin_github_enterprise-web](https://f.cloud.github.com/assets/2364549/1161287/74ebdf04-1fe9-11e3-9d0d-233573326996.png)
![terminal_-__users_dereksorkin_github_enterprise-web](https://f.cloud.github.com/assets/2364549/1161289/8605ef46-1fe9-11e3-83ea-1a32d702c81d.png)

**Comment by mattstyles** [comment]
I still have this bug too, but figured it's probably something to do with running zsh

**Comment by erikkallen** [comment]
I am also running zsh and I have the same problem

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
