### ISSUE TITLE
Rearranging terminal pane breaks it

### ISSUE THREAD

**Issue by gjtorikian** [atom-archive/terminal#14]
1. Open the terminal
2. Split a new pane below it
3. Drag the terminal into that new pane

The terminal container goes all white.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
