### ISSUE TITLE
Upgrade pty.js when windows fixes land

### ISSUE THREAD

**Issue by mcolyer** [atom-archive/terminal#16]
There are many fixes as described in chjj/pty.js#40 (including rows can columns being mixed up and fixing environment variables)

However it's been rebased into chjj/pty.js#47 but that still hasn't landed into a release yet.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
