### ISSUE TITLE
Becomes progressively slower over time

### ISSUE THREAD

**Issue by mcolyer** [atom-archive/terminal#18]
As I start to accumulate a fair amount of back scroll, the session becomes slower and slower. I'm guessing that we don't ever drop history which means we're continually growing the DOM which isn't really sustainable.

**Comment by kaumac** [comment]
+1

**Comment by jdsimcoe** [comment]
+1. I'm getting this same issue... it gets really sluggish over time. The drop history would make sense as I have Grunt output many lines in the Terminal.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
