### ISSUE TITLE
Copy/Paste

### ISSUE THREAD

**Issue by DAddYE** [atom-archive/terminal#24]
Maybe I'm dumb but seems the terminal is unable to copy or paste.

**Comment by probablycorey** [comment]
You're not dumb! This is a bug.

The terminal package is experimental right now, so fixing its bugs are low priority. But thanks for reporting this and open a PR if you code up a fix for it!

**Comment by dazbur** [comment]
I fixed this issue here https://github.com/atom/terminal/pull/37. May be in a naive way since I'm not very familiar with cofeescript/javascript, but it is working.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
