### ISSUE TITLE
It would be nice if I could label the terminal tab

### ISSUE THREAD

**Issue by grimesjm** [atom-archive/terminal#26]
So I've been playing around with the idea of running my external tools in terminal windows in atom. The idea was to self contain my dev setup such that if I close atom all my external dependencies would shut down as well.  In this case I like to run databases, messaging queues, etc on the command line and watch the log while I'm experimenting, testing, developing. 

Being able to label the terminals would be nice such that I could say this is my {DatabaseName} terminal so I don't have to switch between them all to find the one I am using. 

I'm not sure if atom itself allows for that kind of plugability in controlling the tab names.

**Comment by kevinsawicki** [comment]
Yes, the item shown in the pane can return a string from getTitle that will be used as the tab name.

https://github.com/atom/terminal/blob/b42295d02d238030fa710b620f3e474df52396dc/lib/terminal-session.coffee#L45

The pane item can also emit a `title-changed` event to let the tabs know that the title has changed and it should call `getTitle` again.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
