### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by fils** [atom-archive/terminal#29]
Is there an easy way to change the terminal color scheme I am not seeing?

**Comment by EntilZha** [comment]
Same question here

**Comment by ansdma** [comment]
+1 
Though it can be found at `packages/terminal/stylesheet/terminal.css`.

**Comment by kitten** [comment]
My pull request #50 takes some color variables from the UI and Syntax theme. I also made the cursor blinking ;)

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
