### ISSUE TITLE
Heavy CPU usage while open

### ISSUE THREAD

**Issue by kevinsawicki** [atom-archive/terminal#3]
Whenever I have a terminal open it appears that an Atom Helper process is always over 100% CPU.  Once I close the terminal, things return to normal.

@mutle Is this something you've seen?
# While open

![screen shot 2013-07-02 at 9 19 53 am](https://f.cloud.github.com/assets/671378/737659/65771bd0-e333-11e2-8633-99e2509fbb79.png)
# Then closed

![screen shot 2013-07-02 at 9 20 14 am](https://f.cloud.github.com/assets/671378/737660/692c7702-e333-11e2-9328-dcb5bb7ec5e7.png)

**Comment by kevinsawicki** [comment]
Doing some googling I came across [this issue](https://github.com/rogerwang/node-webkit/issues/82) which does mention pty.js.

Perhaps @zcbenz has some insight into this.

**Comment by zcbenz** [comment]
It seems that the `ptyfork` (used by pty.js) isn't working well with atom-shell's message loop integration, somehow it keeps making libuv loop busy. I'll look into it.

**Comment by mutle** [comment]
@zcbenz Any luck with finding the issue with ptyfork yet?

**Comment by zcbenz** [comment]
@mutle I was busy with other issues, will investigate this when I got free.

**Comment by mutle** [comment]
Ok, great!

**Comment by zcbenz** [comment]
I think we encountered a bug of darwin with `ptyfork` and `kevent`, details are submitted in atom-shell's issues list so other people can find it when getting problems of `pty.js`: https://github.com/atom/atom-shell/issues/38.

In short, I will not fix it in atom-shell for now, because getting around of it in atom-shell needs dirty hacks. But we can get around of the `ptyfork` bug by using the `pty.js` module in the node process, in this case, by wrapping the calls of `pty.spawn` in Atom's `Task`, CPU usage would go back to normal.

**Comment by kevinsawicki** [comment]
@zcbenz thanks for looking into this, spawning pty from a node child process did indeed prevent this.
