### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by trombonehero** [atom-archive/terminal#30]
It would be nice if I could change the font size of terminal panes, independently of text editing panes.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
