### ISSUE TITLE
How can I change terminal theme and rename tab with terminal?

### ISSUE THREAD

**Issue by ghost** [atom-archive/terminal#31]
Can I somehow change terminal theme to default dark background with green font 
or rename tab from 'Terminal' to 'Rails server' e.g.? 

It would be cool, if this possibility will be included.
Thanks for cool plugin,
it's really very handy!

**Comment by jgnewman** [comment]
+1. Would love to see a dark theme for terminal.

**Comment by fclement21** [comment]
+1

**Comment by meduza** [comment]
+1

**Comment by GurudayalKhalsa** [comment]
+1

**Comment by kitten** [comment]
My pull request #50 takes some color variables from the UI and Syntax theme. I also made the cursor blinking ;)

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
