### ISSUE TITLE
Wide character support

### ISSUE THREAD

**Issue by rschiang** [atom-archive/terminal#35]
Terminal currently does not support Unicode characters, nor does it display CJK wide characters (replaced with `?`)

Hope this issue be solved. :)

**Comment by rschiang** [comment]
Hmmm... it seems that recent updates of node packages made Terminal show wide characters (though seriously overlapped due to fixed `.terminal pre.line span.character` width. See if we can work something out...

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
