### ISSUE TITLE
ctrl-` to cmd-` on OS X

### ISSUE THREAD

**Issue by anthonator** [atom-archive/terminal#39]
Would it be possible to modify the OS X keybindings to use cmd-` for terminal:open? This looks like a super easy change so I'd be happy to submit a PR but I didn't know if there was some underlying issue with doing this.

**Comment by granda** [comment]
You can always just make a keymap to it. I prefer this method because then I have more flexibility.

```
'body':
  'cmd-`': 'terminal:open'
```

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
