### ISSUE TITLE
cmd-v bug?

### ISSUE THREAD

**Issue by ghost** [atom-archive/terminal#40]
Every time I press cmd-v to paste, the inspector opens instead and the paste never happens. Otherwise, I'm enjoying this plugin.
Stay awesome!
Best regards,

Ben

**Comment by tgraybam** [comment]
Same here. This really limits the value of the Terminal for snippet checking. 
I read here earlier that copy and paste had been fixed, but they still appear broken for me. Thoughts?
Thanks again for your work on this plugin!

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
