### ISSUE TITLE
Selecting text

### ISSUE THREAD

**Issue by ghost** [atom-archive/terminal#41]
I'm unable to select text within the terminal screen.

**Comment by tgraybam** [comment]
Same here (again).

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
