### ISSUE TITLE
Is this right?

### ISSUE THREAD

**Issue by Mobilpadde** [atom-archive/terminal#43]
I've installed your package but it doesn't seem to work properly... Whenever I try to open the terminal I get the devtools instead? I don't know if it's me who's doing something wrong, or?

![skrmbillede 2014-04-28 kl 22 56 33](https://cloud.githubusercontent.com/assets/1170567/2822862/101a1918-cf18-11e3-8456-17773336c119.png)
![skrmbillede 2014-04-28 kl 22 58 20](https://cloud.githubusercontent.com/assets/1170567/2822863/12158a2c-cf18-11e3-8085-ad379090f9ad.png)

**Comment by kasperisager** [comment]
I take it you cloned it directly from GitHub? If so, you'll need to install the dependencies (what the error message is referring to):

``` sh
$ cd $HOME/.atom/packages/terminal && npm install
```

**Comment by Mobilpadde** [comment]
Well, now I'm just getting a white screen instead :D

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
