### ISSUE TITLE
Reload key command errors out

### ISSUE THREAD

**Issue by jdsimcoe** [atom-archive/terminal#45]
When I trying doing `alt` + `cmd` + `r` to trigger a Reload, the Terminal spawns the Web Inspector with this error:

`Uncaught TypeError: Object #<TerminalView> has no method 'reload'`

![screenshot](http://cl.ly/image/3b1k3x0j4704/Image%202014-05-15%20at%206.40.11%20AM.png)

**Comment by jdsimcoe** [comment]
@probablycorey Is there still active work happening on this plugin?

**Comment by izuzak** [comment]
@jdsimcoe Not currently. See also https://github.com/atom/terminal/issues/28#issuecomment-44027534.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
