### ISSUE TITLE
Give a context menu on treeview

### ISSUE THREAD

**Issue by XVincentX** [atom-archive/terminal#47]
It would be very useful to open a terminal not only using a shortcut, but selecting a file, rightclick and "Open terminal from here"

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
