### ISSUE TITLE
Package incompatible

### ISSUE THREAD

**Issue by ironfish** [atom-archive/terminal#48]
Package isn't supported in Atom 0.122.0 because of the Chrome 36 and Node 0.11.13 upgrade.

**Comment by tcarlsen** [comment]
The following packages could not be loaded because they contain native modules that aren't compatible with this version of Atom.

Previous Atom versions shipped with Chrome 31 and Node 0.11.10 but Atom now ships with Chrome 36 and Node 0.11.13.

The packages listed should now ship versions of these native modules that are compatible with Node 0.11.13.

Updates for these packages may already be available that resolve this issue.

If no update is available you may want to notify the package author that their package isn't supported in Atom 0.121.0 because of the Chrome 36 and Node 0.11.13 upgrade.

Terminal 0.28.0Check for UpdateReport IssueDisable Package
Listed below are the incompatible native modules that this package depends on.

pty.js@0.2.4
Error message: Module did not self-register.

**Comment by kitten** [comment]
You just have to load pty.js manually:

``` shell
cd terminal/node_modules
rm -rf pty.js
git clone https://github.com/chjj/pty.js/
cd pty.js
apm install .
cd ../..
apm install .
```

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
