### ISSUE TITLE
When Windows Install other disk Volume,Terminal Init faild! 

### ISSUE THREAD

**Issue by fcharlie** [atom-archive/terminal#51]
Some users of Windows are not installed in C:\ ; like D:\ ..
Start PowerShell from volume:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe 
on: terminal/lib/terminal-process.coffee
Line 6
`shell = 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe'`

Your should Parse environment variables:  

> %SystemRoot%\System32\WindowsPowerShell\v1.0\powershell.exe 

Not start powershell form powershell ,it's unsafe. May someone create a named powershell.exe in your path.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
