### ISSUE TITLE
Inserting/updating/erasing lines still fails sometimes

### ISSUE THREAD

**Issue by mutle** [atom-archive/terminal#6]
I believe this is an issue with either the scrollable region or with the commands for moving lines.

This can be reproduced easily by running `vim` and adding more lines than fit on the screen. In this case it looks like only the last three lines update while the rest of the screen is still showing old lines (enabling line numbers in vim helps). It gets even worse when using ctrl-u and ctrl-d to scroll back up again.

I've seen similar issues with `less`.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
