### ISSUE TITLE
Holding keys only enters a single character

### ISSUE THREAD

**Issue by mcolyer** [atom-archive/terminal#8]
This is pretty easy to reproduce, just open and a shell and press a key. I expect pressing and holding to continue to insert characters.

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
