### ISSUE TITLE
Ncurses/Terminal size reporting

### ISSUE THREAD

**Issue by mcolyer** [atom-archive/terminal#9]
So I think there might be an issue with the way the terminal reports it's size to the console as when I launch `tig` (an ncurses app), it doesn't seem to take up the whole screen.

![screen shot 2013-08-22 at 10 05 51 am](https://f.cloud.github.com/assets/1424/1010553/225b640e-0b4d-11e3-9d16-504786ca9d55.png)

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
